baseURL = "https://glovey.netlify.app"
title = "Gaëtan Lovey"
theme = "minimal-master"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""
defaultContentLanguageInSubdir= true
DefaultContentLanguage = "en"

[languages]
[languages.en]
    languageName = "English"
    title = "Gaëtan Lovey"
    weight = 1

[languages.fr]
    languageName = "Français"
    title = "Gaëtan Lovey"
    weight = 2


[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
    author = "Gaëtan Lovey"
    githubUsername = "#GaetanLovey"
    accent = "black"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    disableLanguageSwitchingButton = false

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 6

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 5

[[menu.main]]
    url = "/curriculum vitæ/"
    name = "Curriculum vitæ"
    weight = 3
    
[[menu.main]]
    url = "/my publications/"
    name = "My publications"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:gaetan.lovey@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/GaetanLovey/"
    name = "github"
    weight = 2


[[menu.icon]]
    url = "https://www.linkedin.com/in/gaetan-lovey/"
    name = "linkedin"
    weight = 4
    


