baseURL = "http://example.org/"
languageCode = "en-us"
title = "Minimalism"
# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-introduction-master"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  themeVariant = "mine"
