baseURL = "https://glportfolio.netlify.app"
languageCode = "en-us"
title = "My Portfolio"
theme = "minimal-master"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
    author = "Gaëtan Lovey"
    description = "Personal portfolio"
    githubUsername = "#GaetanLovey"
    accent = "black"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 4

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 5

[[menu.main]]
    url = "/curriculum vitæ/"
    name = "Curriculum vitæ"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:gaetan.lovey@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/GaetanLovey/"
    name = "github"
    weight = 2


[[menu.icon]]
    url = "https://www.linkedin.com/in/gaëtan-lovey-a3477011b/"
    name = "linkedin"
    weight = 4

