baseURL = "https://glovey.netlify.app"
title = "Gaëtan Lovey"
theme = "minimal-master"
disqusShortname = "" # Supprimer cela pour désactiver les commentaires Disqus
googleAnalytics = ""
defaultContentLanguageInSubdir = true
defaultContentLanguage = "en"

[languages]
[languages.en]
    languageName = "English"
    title = "Gaëtan Lovey"
    weight = 1
    
[[languages.en.menu.main]]
    name = "Home"
    url = "/en/"
    weight = 1

[[languages.en.menu.main]]
    name = "Curriculum vitæ"
    url = "/en/curriculum-vitae/"
    weight = 2

[[languages.en.menu.main]]
    name = "Thesis"
    url = "/en/thesis/"
    weight = 3

[[languages.en.menu.main]]
    name = "Projects"
    url = "/en/projects/"
    weight = 4

[[languages.en.menu.icon]]
    url = "mailto:gaetan.lovey@gmail.com"
    name = "envelope-o"
    weight = 1
    
[[languages.en.menu.icon]]
    url = "https://github.com/GaetanLovey/"
    name = "github"
    weight = 2  
    
[[languages.en.menu.icon]]
    url = "https://www.linkedin.com/in/gaetan-lovey/"
    name = "linkedin"
    weight = 3

[languages.fr]
    languageName = "Français"
    title = "Gaëtan Lovey"
    weight = 2

[[languages.fr.menu.main]]
    name = "Accueil"
    url = "/fr/"
    weight = 1

[[languages.fr.menu.main]]
    name = "Curriculum vitæ"
    url = "/fr/curriculum-vitae/"
    weight = 2

[[languages.fr.menu.main]]
    name = "Thèses"
    url = "/fr/thesis/"
    weight = 3

[[languages.fr.menu.main]]
    name = "Projets"
    url = "/fr/projects/"
    weight = 4

[[languages.fr.menu.icon]]
    url = "mailto:gaetan.lovey@gmail.com"
    name = "envelope-o"
    weight = 1
    
[[languages.fr.menu.icon]]
    url = "https://github.com/GaetanLovey/"
    name = "github"
    weight = 2  
    
[[languages.fr.menu.icon]]
    url = "https://www.linkedin.com/in/gaetan-lovey/"
    name = "linkedin"
    weight = 3
    
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
    author = "Gaëtan Lovey"
    githubUsername = "GaetanLovey" # Supprimer le #
    accent = "black"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # doit correspondre au nom sur Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    disableLanguageSwitchingButton = true
    disableLanguagesButton = true


[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

[[menu.main]]
    url = "/curriculum-vitae/"
    name = "Curriculum vitæ"
    weight = 2
    
[[menu.main]]
    url = "/thesis/"
    name = "Thesis"
    weight = 3

[[menu.icon]]
    url = "mailto:gaetan.lovey@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/GaetanLovey/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/gaetan-lovey/"
    name = "linkedin"
    weight = 4
