name = "Minimal"
license = "MIT"
licenselink = "https://github.com/calintat/minimal/blob/master/LICENSE.md"
description = "Personal portfolio"
homepage = "https://glportfolio.netlify.app"
tags = ["blog", "minimal", "personal", "responsive"]
features = ["responsive"]
min_version = "0.24.1"

[author]
  name = "Gaëtan Lovey"
  homepage = "https://glportfolio.netlify.app"
